version: '3.2'
services:
    app_deepcenter:
        build:
            context: app_deepcenter
            dockerfile: Dockerfile
        container_name: app_deepcenter
        restart: unless-stopped
        env_file:
            - ./.env
        volumes:
            - ${DEEPCENTER_DIR}:/var/www/html/deepcenter
        ports:
            - ${WEB_PORT}:${WEB_PORT}
        networks:
            - dev_network
        links:
            - mysql_dev
            - redis_dev
        command:
            - /bin/bash
            - -c
            - |
              /etc/init.d/php7.4-fpm start &&
              /usr/bin/supervisord
    mysql_dev:
        image: mariadb
        env_file: 
            - ./.env
        container_name: mysql_dev
        restart: unless-stopped
        command: mysqld --sql_mode="" --default-authentication-plugin=mysql_native_password
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin -h 'localhost' -u root -pdeepcenter ping --silent"]
            interval: 30s
            timeout: 30s
            retries: 3
        environment: 
            MYSQL_ROOT_PASSWORD: '${MYSQL_PASS}'
        volumes:
            - ${MYSQL_DIR}:/var/lib/mysql
        ports: 
            - ${MYSQL_PORT}:${MYSQL_PORT}
        expose: 
            - '${MYSQL_PORT}'
        networks:
            dev_network:
                ipv4_address: 172.18.0.20
    redis_dev:
        image: 'redis:latest'
        container_name: redis_dev
        restart: unless-stopped
        env_file: 
            - ./.env
        volumes:
            - ${REDIS_DIR}:/data
        ports: 
            - ${REDIS_PORT}:${REDIS_PORT}
        expose: 
            - '${REDIS_PORT}'
        networks:
            dev_network:
                ipv4_address: 172.18.0.30
networks:
    dev_network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.0.0/16

volumes:
    esdata:
        driver: local